# Generated by Django 3.0.6 on 2020-07-08 06:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enquiry_id', models.CharField(max_length=30)),
                ('student_name', models.CharField(max_length=120)),
                ('address', models.CharField(max_length=250)),
                ('qualification', models.CharField(max_length=120)),
                ('college_name', models.CharField(max_length=120)),
                ('course', models.CharField(max_length=120)),
                ('phone_no', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('enquiry_date', models.DateField(default=datetime.date(2020, 7, 8))),
                ('followup_date', models.DateField()),
                ('statu', models.CharField(choices=[('1', 'call_back'), ('2', 'admitted'), ('3', 'cancel')], max_length=30)),
            ],
        ),
    ]
