# Generated by Django 3.0.6 on 2020-07-14 15:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enq', '0002_auto_20200708_1241'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Batch_code', models.CharField(max_length=120, unique=True)),
                ('Batch_Date', models.DateField()),
                ('Batch_Status', models.CharField(choices=[('1', 'yet_to_begin'), ('2', 'started'), ('3', 'completed')], max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='enquiry_date',
            field=models.DateField(default=datetime.date(2020, 7, 14)),
        ),
    ]
