# Generated by Django 3.0.6 on 2020-07-16 06:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enq', '0005_auto_20200715_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='enquiry_date',
            field=models.DateField(default=datetime.date(2020, 7, 16)),
        ),
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_no', models.CharField(max_length=20, unique=True)),
                ('enquiryid', models.CharField(max_length=50)),
                ('coursefee', models.IntegerField()),
                ('date', models.DateField(default=datetime.date(2020, 7, 16))),
                ('Batch_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enq.Batch')),
            ],
        ),
    ]
