# Generated by Django 3.0.6 on 2020-07-20 07:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enq', '0007_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enquiry',
            old_name='statu',
            new_name='status',
        ),
        migrations.AddField(
            model_name='enquiry',
            name='Batch_code',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='enq.Batch'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='admission',
            name='date',
            field=models.DateField(default=datetime.date(2020, 7, 20)),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='enquiry_date',
            field=models.DateField(default=datetime.date(2020, 7, 20)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateField(default=datetime.date(2020, 7, 20)),
        ),
    ]
