# Generated by Django 3.0.6 on 2020-07-24 04:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enq', '0008_auto_20200720_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='course_name',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='enq.Course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='course_date',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='course_duration',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enquiry',
            name='councillor',
            field=models.CharField(choices=[('1', 'Mender 1'), ('2', 'Mender 2'), ('3', 'Mender 3')], default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enquiry',
            name='sourse',
            field=models.CharField(default=None, max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='admission',
            name='date',
            field=models.DateField(default=datetime.date(2020, 7, 24)),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='enquiry_date',
            field=models.DateField(default=datetime.date(2020, 7, 24)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateField(default=datetime.date(2020, 7, 24)),
        ),
    ]
