# Generated by Django 3.0.6 on 2020-07-24 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enq', '0010_auto_20200724_1055'),
    ]

    operations = [
        migrations.CreateModel(
            name='Councillor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('councillor_name', models.CharField(max_length=60)),
            ],
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='councillor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enq.Councillor'),
        ),
    ]
